### ISSUE TITLE
error????

### ISSUE THREAD

**Issue by yangninghua** [ducha-aiki/wxbs-descriptors-benchmark#2]
![image](https://user-images.githubusercontent.com/32252319/59507055-72b62600-8edc-11e9-9cb0-91cc61bb88ab.png)

**Comment by ducha-aiki** [comment]
Hi,
I think it is the same, as https://github.com/ducha-aiki/wxbs-descriptors-benchmark/issues/1

The most probably reason is that one of the patches is competely one color (black or white), so normalization divides by zero and you get this. Overall, it does not really influence the benchmark, since it is single patch

**Comment by yangninghua** [comment]
Hello Dmytro.Thank you for your answer, I am reading your paper recently, this is a great job, thank you again.




On 06/14/2019 19:44, Dmytro Mishkin wrote:

Hi,
I think it is the same, as #1

The most probably reason is that one of the patches is competely one color (black or white), so normalization divides by zero and you get this. Overall, it does not really influence the benchmark, since it is single patch
